version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    auto-merge: true
    
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    auto-merge: true